- name: Set up Kubernetes
  hosts: kubernetes
  remote_user: ansible_user
  become: yes

  tasks:
    - name: Copy over public ssh key
      ansible.posix.authorized_key:
        user: ansible_user
        state: present
        key: "{{ lookup('file', '/home/ansible_user/.ssh/id_rsa.pub') }}"

    # Begin Kubernetes config
    
